---
# tasks file for roles/osp-instance-delete
- name: add workstation to inventory    
  add_host:
    name: workstation-{{OSP_GUID}}.rhpds.opentlc.com
    groups: workstations
    ansible_user: cloud-user
  register: out



- name: Fetch Instance Info
  os_server_facts:
  register: bip
  delegate_to: workstation-{{OSP_GUID}}.rhpds.opentlc.com


- debug: var=openstack_servers

- debug:
    msg: "{{ item.metadata.deployment_name }}"
  loop: "{{ openstack_servers }}"


- name: Delete instances
  os_server:
    name: "{{ item.name }}"
    state: absent
  when: item.metadata.deployment_name == "QA"
  loop: "{{ openstack_servers }}"
   
- name: Delete router instance
  os_router:
    state: absent
    name: router-instance

- name: delete keypair
  os_keypair:
    name: os_key
    state: absent

- name: remove copied certificates
  file:
    state: absent
    path: "{{ item }}"
  loop:
    - /home/cloud-user/.ssh/openstack.pem
    - /home/cloud-user/.ssh/openstack.pub
  
