---

- name: copy openstack.pub to workstation
  lineinfile:
    path: /home/cloud-user/.ssh/openstack.pub
    create: true
    owner: cloud-user
    mode: 0644  
    line: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd


- name: copy openstack.pem to workstation
  lineinfile:
    path: /home/cloud-user/.ssh/openstack.pem
    create: true
    owner: cloud-user
    mode: 0600  
    line: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAwUwmH6fy7yR6cjKmQXl6F/4x8/yweMgHkQTGC391f5KKXCHr
      UEB2CJIFveiwfQpkAAV/YXqKKbAyvLY+SGYM//3T6n2GqZvkuJs/IyDhbyMJlJXu
      ojNinQbzBqiASolEVaE8EGWTKFs2RKpmhxa0bja2Qg1CfAdy5jQaqd1ELZ2FLhtl
      bYP6veFqpb+5xogSf209B4T467BRlybNvRd+eKyt16fSnijvUQdj2DYCCdtihTTm
      dyFeuyOW3driUFxxLkGKgHpx4f3CLdRonDlRhyq/UUDp4M+NPd/7blX4sISMimVV
      ruF5txvMer/Z8oOIn4uV0gTb1wQrl0nYr7/snQIDAQABAoIBABw9qug/GnA0DSu4
      GLBCNkNhIR07kvDikLBwWRr+8UTFPS++yOl9sYEJDIu1fmuWZAvYwcaVJ7B1jMQj
      gDAFsOqJxDdjRZRsMVuDWxMfz6/0F4c87JOIHGVCyaj0X2IEchZsqyDeJkTkJqab
      msUr3QqpNbGqzEbgs7nMbQTaTga31r0SY2IND0p8BfheUfAEZz5Q9EWIoeAvjL8v
      3apSO+ffRzzJy3Z40m3ZxKRVq5pDEzfWPYKkzKsTH/n2kzs40RYDNoTt6Hcpc000
      oV2pz5sNrbHcT77G411dQd5c2Fa0k9rgx5DHIxx2w4/Mlq6ufaYAWOO9kwXGHN1I
      tOvKyCUCgYEA7weJ4RrHdwLv0TbQamYkXg0Mvkg4Ffiafv2CssVb54NzzAtjktD5
      WNz9C3sCe3JyS6DQXJEOLpXAWOcwT3QfOPeJUFVVibkB5v07FAM6VShCACyaeQ8/
      NNyrQldnsVtLuf3aiHUH+AXuh2LuFEQX5/bhBvqI03dO3EHASDvsyyMCgYEAzwVp
      ewHY5j0q9plN12bZvRcRNM7xkjX304r/+aY3bRYF0BHp7WSjrejmQ8Y9ZKNeyHoa
      jNDrE0Yy2RXMoWkH+rmPHovPqTiSxSsX1NEqDQEcU+O1ISRgPivgjQnPl+a/9Z1l
      VQ7kcdkfy0tPO5TGk1uV66QclynAM4SNHV24xT8CgYEAnQ3R/XMv/jWSx1+Bv3dP
      i/B9IAWpvF31fV0q5DWi9lI74qTVDyF5xHanWUTA08XV7XVDkp7It7kzgfadmocN
      AMw8j+kR5AUIh/J5P+QDDvL9ssmb0dE/0YbwjA2MF0+KSTHPxftHeiLDoHdTQUOg
      hYyEPKafAnsQ+M3G/m9JXgsCgYBcHkJjc9z6BnnZpTnYAXIeC+eiIfuoXc9bGFzy
      z52WMth/T5lSAxg6SIo92jZzU6bXek3aHxSbTP9PTb3yjPP6AxvGMdxDpmLYzWYb
      Ur9tbfMW+RoeFzukLo4K9DSlmQ4N0u3GPYw1hLH7GhW1o2wBIh3B7xKxyOg3hGHu
      kUeorQKBgQC684OaGy2X1MO+iiIv0YgkCjECdyFMLtAjEp2nPDqu42/QE5gxzEq4
      mAj94U2I2/DUBCKvlSwB2a+n6vkgWgkOMkbfi6jYC5J3ktrMqK4pWWQ/GPSijekt
      ZFQOKTpno3xXhUsz9Ts4shClaG+BscqHeX0yfs1hknbsCSNuCnZxmQ==
      -----END RSA PRIVATE KEY-----



- name: Create keypair
  os_keypair:
    state: present
    name: os_key
#     key: /home/cloud-user/.ssh/openstack.pem
    public_key_file: /home/cloud-user/.ssh/openstack.pub


- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    name: "{{ item.value.name }}"
    state: "{{ item.value.state }}"
    image: "{{ item.value.image }}"
#     key_name: "{{ item.value.key_name }}"
    key_name: os_key
    flavor: "{{ item.value.flavor }}"
    security_groups: "{{ item.value.security_group }}"
    network: int_network
    meta:
      group: "{{ item.value.meta[0].group }}"
      deployment_name: "{{ item.value.meta[0].deployment_name }}"
    userdata: |
      {% raw %}#!/bin/bash
      cat << EOF > /etc/yum.repos.d/internal.repo
      [rhel-7-server-rpms]
      name=Red Hat Enterprise Linux 7
      baseurl=http://{{ repo_ip }}/repos/rhel-7-server-rpms
      enabled=1
      gpgcheck=0
      
      [rhel-7-server-rh-common-rpms]
      name=Red Hat Enterprise Linux 7 Common
      baseurl=http://{{ repo_ip }}/repos/rhel-7-server-rh-common-rpms
      enabled=1
      gpgcheck=0
      
      [rhel-7-server-extras-rpms]
      name=Red Hat Enterprise Linux 7 Extras
      baseurl=http://{{ repo_ip }}/repos/rhel-7-server-extras-rpms
      enabled=1
      gpgcheck=0
      
      [rhel-7-server-optional-rpms]
      name=Red Hat Enterprise Linux 7 Optional
      baseurl=http://{{ repo_ip }}/repos/rhel-7-server-optional-rpms
      enabled=1
      gpgcheck=0
      {% endraw %}

  loop: "{{ osp_servers|dict2items }}"

- name: Add logical router to the project
  os_router:
    state: present
    name: router-instance
    network: ext_network


# - debug:
#     msg: "{{item.value.meta[0].deployment_name}}"
#   loop: "{{osp_servers|dict2items}}"

- name: Add floating IPs to Openstack instances
  os_floating_ip:
    state: present
    reuse: true
    server: "{{ item.value.name }}"
    network: ext_network
    wait: true
    timeout: 180
  loop: "{{ osp_servers|dict2items }}"
  register: floaters

- name: Retrieve instance details from Openstack environment
  os_server_facts:
  register: serverfacts
# - debug: var=floaters

- name: Wait for servers to be available on port 22
  wait_for:
    host: "{{ item.public_v4 }}"
    port: 22
    delay: 10
    timeout: 300
  loop: "{{ serverfacts.ansible_facts.openstack_servers }}"
  when: item.metadata.deployment_name == "QA"



