---
# - name: install {{ component }}
#   yum:
#     name: "{{ component }}"
#     state: latest
# 
# - name: enable {{ component }} at boot
#   service:
#     name: "{{ component }}"
#     enabled: yes
# - name: start {{ component }}
#   service:
#     name: "{{ component }}"
#     state: restarted
# 
